zmq_setup:
    timeout: 1000
J1_A:
    control_mode: idle
    max_current_A: 30.0
    pid:
        impedance:
            - 500.0
            - 20.0
            - 1.0
            - 0.025
            - 0.99
        position:
            - 1000.0
            - 0.0
            - 30.0
    pos_offset: 0
    sign: 1
gripper_A_motor:
    control_mode: idle
    pid:
        position:
            - 100000.0
            - 0.0
            - 1.0
    pos_offset: 0
    sign: 1
