zmq_setup:
    timeout: 1000
J1_A:
    control_mode: D4_impedance_ctrl
    pid:
        impedance:
            - 500.0
            - 20.0
            - 1.0
            - 0.025
            - 0.99
        position:
            - 1000.0
            - 0.0
            - 30.0
gripper_A_motor:
    control_mode: 3B_motor_pos_ctrl
    pid:
        position:
            - 100000.0
            - 0.0
            - 1.0