xbotcore_devices:
    joint_ec:
        names: []
        thread: rt_main
        params:
            robot_name: &id002
                value: NoNe
                type: string
            config_ec_idle:
                value: $PWD/../joint_config/ModularBot_idle.yaml
                type: yamlfile
            config_ec_imp:
                value: $PWD/../joint_config/ModularBot_impd4.yaml
                type: yamlfile
            joint_id_map: &id001
                value: $PWD/../../joint_map/ModularBot_joint_map.yaml
                type: yamlfile
            ignore_id:
                type: vector<int>
                value:
                    - '6'
    joint_master:
        master: true
        thread: rt_main
